### PR TITLE
Update index.rst

### PR DESCRIPTION
**Pull request by peger089**
Update to the PSF_TABLE description.

### CODE REVIEW

**Comment by mimayer** [comment]
I have a comment about the name "RAD_LO/HI", which I don't think is very meaningful. At the moment in gammalib, we use "delta" to specify the angle from the source position. We could here use DELTA_LO/HI instead.

Probably mostly irrelevant but just my taste: for the order of the columns I'd prefer: "ENERGY, THETA, DELTA

**Comment by cdeil** [comment]
@mimayer The order of the columns and the names are taken 1:1 from the RPSF OGIP spec.
I've updated the description to explain this more clearly:
http://gamma-astro-data-formats.readthedocs.org/en/latest/irfs/psf_table/index.html

OK to keep these column names?

**Comment by cdeil** [comment]
@peger089 - As discussed, I've changed to column name "RPSF" to match the OGIP spec and fixed the normalisation Sphinx Latex formula:
http://gamma-astro-data-formats.readthedocs.org/en/latest/irfs/psf_table/index.html

This now looks good to me.

@mimayer -- Maybe we should start a new separate issue about consistent axis names (or a table with recommended / in use axis names in the docs)?

**Comment by mimayer** [comment]
Ok, axis names are fine with me. Didn't know they existed already for OGIP. Nevertheless, we shouldn't be guided by OGIP too much since we invent our own stuff :)

**Comment by cdeil** [comment]
I'll make a new issue or pull request about axis names in a few minutes ... checking if we already have inconsistency in some places or not ... agreed we don't have to follow OGIP (but it would be the default I use if there's no other arguments / constraints).

**Pull request merged**
